---
  - name: "Installation of a New Ansible Controller"
    hosts: localhost
    gather_facts: false

    roles:
      - { role: ansible-vars}
      - { role: aws-ec2-linux}

---
- name: "Install Ansible Controller"
  hosts: all
  gather_facts: False

  roles:
    - { role: ansible-vars}
    - { role: ansible-install}
