---
  - name: "Installation of a New Ansible Controller"
    hosts: localhost
    gather_facts: false

    roles:
      - { role: ansible-vars}
      - { role: aws-ec2-linux}

  - name: "Install Ansible using Ec2 New Instances"
    include: custom_hosts.yml
