---
  - name: CentOs | Installing EPEL Repo
    yum:
      name: "epel-release"
      state: "present"

  - name: CentOs | Installing Pre-Reqs
    yum:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
      - 'python-pip'
      - 'python-devel'
      - 'gcc'
      - 'git'
      - 'libffi-devel'
      - 'openssl-devel'
      - 'krb5-devel'
      - 'krb5-workstation'

  - name: CentOs | Upgrading Pip
    pip:
      name: "pip"
      state: "latest"
    become: true

  - name: CentOs | Installing Ansible
    pip:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
      - 'ansible'
      - 'pywinrm'
      - 'boto'


  - name: CentOs | Installing Kerberos Components
    pip:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
      - 'kerberos'
      - 'requests-kerberos'


  - name: CentOs | Upgrading Setup Tools
    pip:
      name: "setuptools"
      state: "latest"
    become: true

  - name: Ansible | Version
    shell: ansible --version
    register: ansible_installed_version

  - set_fact:
      application_tag: '{ "ansible-version":"{{ ansible_installed_version.stdout_lines[0] }}" }'

  - local_action:
      module: ec2_tag
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "us-east-1"
      resource: "{{ item.id }}"
      tags: "{{ application_tag }}"
      state: present
    with_items:  "{{ hostvars['localhost']['instances'] }}"
