---
  - name: "Start Installation Of <Your System goes here>"
    hosts: redis
    gather_facts: false
    remote_user: root
    become: yes    

    roles:
      - { role: common}
      - { role: redis}
