  - name: AWS-EXISTS | Discover Instances By Tag
    ec2_remote_facts:
      region: "eu-central-1"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      filters:
        instance-state-name: running
        "tag:Version": "{{ version }}"
        "tag:Type": "{{ type }}"
        "tag:Env": "{{ environment }}"
    register: ec2


  - debug: var=ec2

  - name: AWS-EXISTS | Wait for SSH
    wait_for:
      host: "{{ item.private_ip_address }}"
      port: 22
      timeout: 600
    with_items: "{{ ec2.instances }}"

  - name: AWS-EXISTS | Add New Instances to centos Group
    add_host:
      name: linux-temp-{{ item.id }}
      ansible_host: "{{ item.private_ip_address }}"
      groups: centos
    with_items: "{{ ec2.instances }}"

  - set_fact:
      instances: "{{ ec2.instances }}"
