  - name: AWS-LINUX-NEW | Find Latest Amazon Linux AMI
    ec2_ami_find:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "us-east-1"
      name: "amzn-ami-hvm-*-gp2"
      sort: name
      owner: amazon
      sort_order: descending
      no_result_action: fail
    register: ami_find

  - name: AWS-LINUX-NEW | Start 1 instances
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      instance_type: "m3.medium"
      image: "{{ ami_find.results[0].ami_id }}"
      wait_timeout: 900
      key_name: "{{ aws_key_name }}"
      wait: yes
      group: "ansible-controller"
      count: "1"
      region: "us-east-1"
      instance_tags:
        Name: "Ansible Controller"
    register: ec2

  - debug: var=ec2

  - name: AWS-LINUX-NEW | Wait for SSH
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      timeout: 600
    with_items: "{{ ec2.instances }}"

  - name: AWS-LINUX-NEW | Add New Instances to aws-linux Group
    add_host:
      name: linux-temp-{{ item.id }}
      ansible_host: "{{ item.public_ip }}"
      groups: aws-linux
    with_items: "{{ ec2.instances }}"

  - set_fact:
      instances: "{{ ec2.instances }}"
