- name: "REDIS | Install redis"
  yum: >
    name=redis
    state=installed
    enablerepo=epel


#- name: "REDIS | Set redis.conf"
#  template: >
#    src=redis.conf
#    dest="/etc/redis.conf"
#    mode=0644
#    owner=root
#    group=root
#  notify:
#    - REDIS | Restart Redis


- name: "REDIS | Make sure Redis is running"
  service: >
    name=redis
    enabled=yes
    state=started
